import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

const blog = ({posts}) => {
  // const [Posts, setPosts] = useState([]);

  // useEffect(() => {
  //   axios
  //     .get("https://jsonplaceholder.typicode.com/posts")
  //     .then((res) => {
  //       setPosts(res.data);
  //     })
  //     .catch((err) => {
  //       console.log(err);
  //     });
  // }, [setPosts]);

  return (
    <>
    <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <div>
        {posts?.length===0 &&(

        <div style={{
            display:"flex",
            justifyContent:"center",
            alignItems:"center",
            height:"100vh",
            fontSize:"30px"
        }}>Loading...</div>
        )}
      <div className="container">
        <h1 className="blog">Blog</h1>
        {posts?.map((post) => (
          <div key={post.id} className="posts">
            <Link href={`/posts/${post.id}`}>
              <h1>{post.title}</h1>
            </Link>
            <p>{post.body}</p>
          </div>
        ))}
      </div>
    </div>
    </>
  );
};

export async function getStaticProps(){
  const res = await axios.get("https://jsonplaceholder.typicode.com/posts")

  return{
    props:{
      posts:res.data
    },
    revalidate:1,
    
  }
}

export default blog;
