import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Link
          href="/blog"
          style={{
            borderBottom: "1px solid white",
          }}
        >
          <h1>Blog</h1>
        </Link>
        <Link
          href="/posts/sport"
          style={{
            borderBottom: "1px solid white",
          }}
        >
          <h1>Sport</h1>
        </Link>
        <Link
          href="/posts/health"
          style={{
            borderBottom: "1px solid white",
          }}
        >
          <h1>Health</h1>
        </Link>

        <Link href={"https://www.linkedin.com/in/mahmoud-h-7a3895195/"} target="_blank">
          <h3
            style={{
              borderBottom: "1px solid white",
              marginTop: "20px",
              cursor: "pointer",
            }}
          >
            Created By{" "}
            <span
              style={{
                color: "red",
              }}
            >
              Mahmoud Hamdy
            </span>{" "}
            <span>❤️</span>
          </h3>
        </Link>
      </main>
    </>
  );
}
